# Generated by Django 3.1.3 on 2020-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_updated',
            field=models.BooleanField(default=False),
        ),
    ]
