# Generated by Django 3.1.3 on 2020-12-14 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('images', models.ImageField(upload_to='products/')),
                ('tipo', models.CharField(choices=[('GM', 'Console Game'), ('YGOC', 'Yugioh Card'), ('MGC', 'Magic Card'), ('PKMNC', 'Pokémon Card')], max_length=30)),
                ('country', models.CharField(max_length=120)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('Language', models.CharField(max_length=120)),
                ('Card_condition', models.CharField(choices=[('NM', 'NM'), ('LP', 'LP'), ('MP', 'MP'), ('HP', 'HP'), ('D', 'D'), ('None', 'None')], max_length=30)),
                ('Game_condition', models.CharField(choices=[('Nw', 'New'), ('LN', 'Like-New'), ('US', 'Used'), ('None', 'None')], max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
